# Generated by Django 6.0.3 on 2026-03-14 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('room', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('passed', 'Passed'), ('failed', 'Failed'), ('retake', 'Retake')], default='upcoming', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.subject')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
